/**
 * grove completions — generate shell completion scripts.
 *
 * Usage:
 *   grove completions bash   # output bash completion script
 *   grove completions zsh    # output zsh completion script
 *   grove completions fish   # output fish completion script
 *
 * Install:
 *   grove completions bash >> ~/.bashrc
 *   grove completions zsh >> ~/.zshrc
 *   grove completions fish > ~/.config/fish/completions/grove.fish
 */

import { COMMANDS, type CommandMeta } from "../registry.js";

/** Supported shells. */
export type Shell = "bash" | "zsh" | "fish";

const SHELLS: readonly Shell[] = ["bash", "zsh", "fish"];

/**
 * Parse completions arguments.
 */
export function parseCompletionsArgs(args: readonly string[]): Shell {
  const shell = args[0];
  if (!shell) {
    throw new Error(`Shell argument required.\n\nUsage: grove completions <${SHELLS.join("|")}>`);
  }
  if (!SHELLS.includes(shell as Shell)) {
    throw new Error(`Unknown shell '${shell}'. Supported: ${SHELLS.join(", ")}`);
  }
  return shell as Shell;
}

/**
 * Generate a completion script for the given shell.
 */
export function generateCompletions(shell: Shell, commands?: readonly CommandMeta[]): string {
  const cmds = commands ?? COMMANDS;
  switch (shell) {
    case "bash":
      return generateBash(cmds);
    case "zsh":
      return generateZsh(cmds);
    case "fish":
      return generateFish(cmds);
  }
}

// ---------------------------------------------------------------------------
// Bash
// ---------------------------------------------------------------------------

function generateBash(commands: readonly CommandMeta[]): string {
  const cmdNames = commands.map((c) => c.name).join(" ");

  // Top-level case arms: complete subcommand names + top-level flags
  const topCaseEntries = commands
    .map((cmd) => {
      const flags = cmd.flags.map((f) => `--${f}`).join(" ");
      const subs = cmd.subcommands ? cmd.subcommands.map((s) => s.name).join(" ") : "";
      const completions = [subs, flags].filter(Boolean).join(" ");
      return `      ${cmd.name}) COMPREPLY=( $(compgen -W "${completions}" -- "$cur") ) ;;`;
    })
    .join("\n");

  // Nested case arms for subcommands: dispatch on COMP_WORDS[2]
  const subCaseEntries = commands
    .filter((cmd) => cmd.subcommands && cmd.subcommands.length > 0)
    .flatMap((cmd) => {
      const subArms = (cmd.subcommands ?? [])
        .filter((sub) => sub.flags.length > 0)
        .map((sub) => {
          const subFlags = sub.flags.map((f) => `--${f}`).join(" ");
          return `          ${sub.name}) COMPREPLY=( $(compgen -W "${subFlags}" -- "$cur") ) ;;`;
        });
      if (subArms.length === 0) return [];
      return [
        `      ${cmd.name})`,
        `        case "\${COMP_WORDS[2]}" in`,
        ...subArms,
        `          *) ;;`,
        `        esac`,
        `        ;;`,
      ];
    })
    .join("\n");

  return `# grove bash completion — generated by 'grove completions bash'
_grove_completions() {
  local cur prev commands
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  commands="${cmdNames}"

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "$commands --help --version" -- "$cur") )
    return 0
  fi

  # Subcommand flag completion (COMP_CWORD >= 3)
  if [[ \${COMP_CWORD} -ge 3 ]]; then
    case "\${COMP_WORDS[1]}" in
${subCaseEntries}
      *) ;;
    esac
    [[ \${#COMPREPLY[@]} -gt 0 ]] && return 0
  fi

  case "\${COMP_WORDS[1]}" in
${topCaseEntries}
      *) ;;
  esac
  return 0
}
complete -F _grove_completions grove
`;
}

// ---------------------------------------------------------------------------
// Zsh
// ---------------------------------------------------------------------------

function generateZsh(commands: readonly CommandMeta[]): string {
  const cmdDescriptions = commands
    .map((cmd) => `    '${cmd.name}:${cmd.description}'`)
    .join(" \\\n");

  // Generate per-command helper functions for commands with subcommands
  const helperFunctions: string[] = [];

  const caseEntries = commands
    .map((cmd) => {
      const subcmds = cmd.subcommands ?? [];
      if (subcmds.length > 0) {
        // Commands with subcommands get a dedicated helper function
        const subDescriptions = subcmds
          .map((s) => `      '${s.name}:${s.description}'`)
          .join(" \\\n");

        const subCaseArms = subcmds
          .map((sub) => {
            if (sub.flags.length === 0) return `      ${sub.name}) ;;`;
            const subFlags = sub.flags.map((f) => `'--${f}[${f}]'`).join(" ");
            return `      ${sub.name}) _arguments ${subFlags} ;;`;
          })
          .join("\n");

        helperFunctions.push(`_grove_${cmd.name}() {
  local -a subcommands
  subcommands=(
${subDescriptions}
  )

  _arguments -C '1:subcommand:->subcmd' '*::arg:->subargs'

  case $state in
    subcmd)
      _describe '${cmd.name} subcommand' subcommands
      ;;
    subargs)
      case $line[1] in
${subCaseArms}
      esac
      ;;
  esac
}`);
        return `    ${cmd.name}) _grove_${cmd.name} ;;`;
      }

      // Simple commands: inline _arguments
      const flags = cmd.flags.map((f) => `'--${f}[${f}]'`).join(" ");
      if (!flags) return `    ${cmd.name}) ;;`;
      return `    ${cmd.name}) _arguments ${flags} ;;`;
    })
    .join("\n");

  const helpers = helperFunctions.length > 0 ? `${helperFunctions.join("\n\n")}\n\n` : "";

  return `#compdef grove
# grove zsh completion — generated by 'grove completions zsh'
${helpers}_grove() {
  local -a commands
  commands=(
${cmdDescriptions}
  )

  _arguments -C '1:command:->cmd' '*::arg:->args'

  case $state in
    cmd)
      _describe 'grove command' commands
      ;;
    args)
      case $line[1] in
${caseEntries}
      esac
      ;;
  esac
}

_grove "$@"
`;
}

// ---------------------------------------------------------------------------
// Fish
// ---------------------------------------------------------------------------

function generateFish(commands: readonly CommandMeta[]): string {
  const lines: string[] = [
    "# grove fish completion — generated by 'grove completions fish'",
    "",
    "# Disable file completions for grove",
    "complete -c grove -f",
    "",
    "# Top-level commands",
  ];

  for (const cmd of commands) {
    lines.push(
      `complete -c grove -n '__fish_use_subcommand' -a '${cmd.name}' -d '${cmd.description}'`,
    );
  }

  lines.push("");
  lines.push("# Command flags");

  for (const cmd of commands) {
    for (const flag of cmd.flags) {
      lines.push(`complete -c grove -n '__fish_seen_subcommand_from ${cmd.name}' -l '${flag}'`);
    }

    if (cmd.subcommands) {
      for (const sub of cmd.subcommands) {
        lines.push(
          `complete -c grove -n '__fish_seen_subcommand_from ${cmd.name}' -a '${sub.name}' -d '${sub.description}'`,
        );
        // Subcommand-specific flags — scope by both parent AND sub to avoid
        // name collisions (e.g. bounty list vs outcome list)
        for (const flag of sub.flags) {
          lines.push(
            `complete -c grove -n '__fish_seen_subcommand_from ${cmd.name}; and __fish_seen_subcommand_from ${sub.name}' -l '${flag}'`,
          );
        }
      }
    }
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Handle the `grove completions` CLI command.
 */
export async function handleCompletions(args: readonly string[]): Promise<void> {
  const shell = parseCompletionsArgs(args);
  const script = generateCompletions(shell);
  console.log(script);
}
